version: '3.3'
services:
  php:
    container_name: php
    image: registry.cn-hangzhou.aliyuncs.com/yxhdoc/php-fpm-7.2:v2
    tty: true
    restart: always
    expose:
      - "9000"
    environment:
      TZ : 'Asia/Shanghai'
    volumes:
      - ./html:/data/html
      - ./log/php:/var/log/php-fpm
    depends_on:
      - mysql
      - redis
    links:
      - "mysql:mysql"
      - "redis:redis"
  nginx:
    container_name: nginx
    image: nginx:1.18.0
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ : 'Asia/Shanghai'
    volumes:
      - ./html:/data/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
    links:
      - "php:php"
      - "mysql:mysql"
      - "redis:redis"
  mysql:
    container_name: mysql
    image: mysql:5.7.21
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      TZ : 'Asia/Shanghai'
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    container_name: redis
    image: redis:6.2.7
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes 
