version: '3.3'
services:
  php:
    container_name: php
    image: php:7.0-fpm
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - ./html:/data/html
      - ./log/php:/var/log/php-fpm
    depends_on:
      - mysql
      - redis
    links:
      - "mysql:mysql"
      - "redis:redis"
  nginx:
    container_name: nginx
    image: daocloud.io/library/nginx:1.18.0
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/data/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
    links:
      - "php:php"
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.7.21
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes 
#  phpmyadmin:
#    container_name: phpmyadmin
#    image: daocloud.io/daocloud/phpmyadmin
#    expose:
#      - '80'
#    ports:
#      - "8080:80"
#    environment:
#      - PMA_ARBITRARY=0
#      - PMA_HOST=mysql
#    depends_on:
#      - mysql
#    links:
#      - mysql:mysql
#  phpredisadmin:
#    container_name: phpredisadmin
#    image: erikdubbelboer/phpredisadmin
#    expose:
#      - '80'
#    ports:
#      - "8081:80"
#    environment:
#      - REDIS_1_HOST=redis
#      - REDIS_1_NAME=redis
 #   depends_on:
 #     - redis
 #   links:
 #     - redis:redis
